language: objective-c
osx_image: xcode8.1
xcode_workspace: welcome-ios.xcworkspace
xcode_scheme: welcome-ios
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#feedhenry"

script:
  - xcodebuild clean build -workspace welcome-ios.xcworkspace -scheme welcome-ios -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

branches:
  only:
    - master
    - xcode8